FROM qnib/alpn-jre8
ADD clj-kstream-string-long-window-aggregate.jar /usr/share/clj-kstream/clj-kstream-string-long-window-aggregate.jar
ENTRYPOINT ["java", "-jar", "/usr/share/clj-kstream/clj-kstream-string-long-window-aggregate.jar"]
CMD []